[package]
name = "kooixc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Kooix language checker MVP (AI-native strong typing)"
readme = "README.md"
repository = "https://github.com/telagod/Kooix"
homepage = "https://github.com/telagod/Kooix"
documentation = "https://github.com/telagod/Kooix/blob/main/README.en.md"
keywords = ["compiler", "language", "cli", "ai"]
categories = ["compilers", "command-line-utilities"]
rust-version = "1.78"

[lib]
name = "kooixc"
path = "src/lib.rs"

[[bin]]
name = "kooixc"
path = "src/main.rs"
